specta/specta

- README.md
As per #106, installation instructions are currently broken.
> Fixes CocoaPods installation instructions. 

- Specta/Specta/SpectaDSL.h
OBJC_EXTERN specifies how to mangle method names.
Correct name mangling makes linker more happy.
> Add support for ObjC++

- Specta/Specta.xcodeproj/project.pbxproj
- Specta/Specta/SPTExampleGroup.m
- Specta/Specta/SPTExcludeGlobalBeforeAfterEach.h
This PR takes a little bit different approach than https://github.com/specta/specta/pull/86. Rather than whitelisting specific classes via protocol I've added a protocol that allows blacklisting of certain classes. From what I can tell the OCMock issue can be fixed by creating a category that adds the protocol to `OCMockObject`. Same goes for Google Analytics https://github.com/specta/specta/issues/116. 
There is one thing that I really don't like but I currently have no better idea, which is where to place code that adds this protocol to our beloved `UIAccessibilitySafeCategory__NSObject`. Ideas are welcomed.
> Attempt to fix OCMock 3 incompatibility

- Specta/Specta/XCTestCase+Specta.m
- Specta/SpectaTests/AsyncSpecTest.m
`-[XCTestCase _dequeueFailures]` will only process failures if it is called from the main thread. If an asynchronous test makes assertions on another thread, that will not be the case, leading to masked failures. This PR implements a workaround by swizzling the method and calling the original method on the main thread if called from another thread. It also provides a spec for assertions on a background queue.
This should fix #123, #96 and possibly #44 - note that the descriptions of the problem in most of those issues are out of date, because of the implementation changes regarding asynchronous testing.
> Ensure failures are delivered on the main thread

- Specta/Specta/SpectaUtility.h
I had originally tried to fix code within Expecta (https://github.com/specta/expecta/blob/master/Expecta/ExpectaSupport.m#L165) by using mainThread instead of currentThread. However this did not work for me in the current code base.
I was able to fix my multithreaded error reporting using these macro definitions.
> Fix for reporting specta/expecta failures on the main thread.

- Rakefile
I work in an environment where I use multiple versions of Xcode.  I often use the `DEVELOPER_DIR` to control which version of Xcode I am using on a per-command basis.
Using `xcrun` to locate the active Xcode command-line tools is a good practice.  It can also help to quickly confirm that a behavior works as expected across Xcode versions.
```
$ cd specta
$ DEVELOPER_DIR=/Xcode/5.1.1/Xcode.app rake test
$ DEVELOPER_DIR=/Xcode/6.1.1/Xcode.app rake test
$ DEVELOPER_DIR=/Xcode/6.2/Xcode-Beta.app rake test
$ DEVELOPER_DIR=/Xcode/6.3/Xcode-Beta.app rake test
```
```
DEVELOPER_DIR
Overrides the active developer directory. When DEVELOPER_DIR
is set, its value will be used instead  of  the  system-wide
active developer directory.
```
> Run Xcode command line tools with xcrun

- Rakefile
**FORCE PUSHED** Tue Mar 3 14:24 CET
I am blessed or cursed (take your pick) with many code-signing identities.
The `$ rake` command fails for me out of the box.
```
Running /usr/bin/codesign <snip>
Warning: --resource-rules has been deprecated in Mac OS X >= 10.10!
iPhone: ambiguous (matches "iPhone Developer: My Identity (9<snip>L)" and
"iPhone Developer: Some Client (8<snip>Z)" 
in /<snip>/login.keychain)
rake aborted!
** BUILD FAILED **
Running /usr/bin/codesign <snip>
Warning: --resource-rules has been deprecated in Mac OS X >= 10.10!
iPhone: ambiguous (matches "iPhone Distribution: XXXXX" and 
"iPhone Developer: Some Client (8<snip>Z)" 
in /<snip>/login.keychain)
rake aborted!
** BUILD FAILED **
```
I don't have a great way of handling this in open-source projects.  One way is to …
> Add ENV var to control signing identity in rake build task

- CONTRIBUTING.md
I maintain several open source projects.  I really don't like it when users ask questions in GitHub issues. 
I had a question today about Specta:  **Defining a variable that can be used across all examples in a group: like `let`** #137.  I felt genuinely terrible asking in a GitHub issue, but I didn't see any documentation that mentioned I should ask my question on Stack Overflow.
This PR adds a CONTRIBUTING.md doc that directs users to Stack Overflow.
I really like cucumber's [CONTRIBUTING.md document](https://github.com/cucumber/cucumber/blob/master/CONTRIBUTING.md).  
Maybe the wiki home page could point people with questions to Stack Overflow as well?
> Add a contributing doc

- CHANGELOG.md
> Makes it easy to skip the beforeAll/afterAll functions for specific classes
The `SPTExcludeGlobalBeforeAfterEach` exlcludes `+ beforeEach` and `+ afterEach` implemented by the classes that conform to it. There's no global beforeAll/aftreAll (yet?).
> Fix typo in CHANGELOG for version 0.4

- Specta/Specta.xcodeproj/project.pbxproj
- Specta/Specta/SPTExampleGroup.m
- Specta/SpectaTests/PendingSpecTest5.m
This patch resets (if needed) and increments the number of ran test cases also for pending test cases.
It fixes a problem that the `afterAll` or `beforeAll` blocks might ran multiple times.
This would happen when you declare pending blocks as your first or last blocks
In this case of `afterAll`, the comparison `group.ranExampleCount + group.pendingExampleCount == group.exampleCount` will always be true, leading to the multiple execution of the `afterAll` blocks.
The same is applied for `beforeAll`. If the pending blocks are declared before the other test cases, the comparison `group.ranExampleCount == 0` will be true and the `beforeAll` blocks will be called multiple times.
Fixes #124
> Increment the ran test cases number for pending 

- README.md
1. Add subsections to install manually and via Cocoapods
2. Move the manual install section up
3. Move the note about other matchers and mock framework to the end of examples.
This way it gets more similar to the Expecta's readme.
You can see the result in [here](https://github.com/dbarden/specta/blob/readme/README.md).
I didn't know where to put the notes about matchers and mock frameworks, since they are not specific to the install of Specta, so I just moved to the end of the Example section. Guess it fits better there, since we're talking about the usage of Specta. But let me know what you think.
> Small README reorganization

- CHANGELOG.md
- Specta/Specta.xcodeproj/project.pbxproj
- Specta/Specta/SPTExampleGroup.m
- Specta/Specta/SPTExcludeGlobalBeforeAfterEach.h
- Specta/Specta/SPTGlobalBeforeAfterEach.h
- Specta/Specta/SPTIncludeGlobalBeforeAfterEach.h
- Specta/SpectaTests/SequenceTest.m
This change set addresses #148
When running global before and after hooks, we were picking up any class that implemented `+beforeEach` and/or `+afterEach`. You could opt-out by conforming to the `SPTExcludeGlobalBeforeAfterEach` protocol. This could cause difficult to debug failures if unwanted hooks were included, especially if they involved classes that the developer did not control.
This commit reverses the approach, creating a `SPTIncludeGlobalBeforeAfterEach` protocol, which `SPTExampleGroup` implements. With this change, we only select classes that implement `SPTIncludeGlobalBeforeAfterEach` for running global `+beforeEach` and/or `+afterEach`. You can opt-in by implementing the protocol.
This change seems to fix my spec failures, but I am not actually using global before/after …
> Whitelist classes for global before/after hooks

- Specta/Specta.xcodeproj/project.pbxproj
When attempting to import Specta as a dependency using Carthage, building the `Specta-iOS` scheme fails with the following error:
```
$ cat Cartfile
github "specta/specta"
$ carthage bootstrap
*** No Cartfile.resolved found, updating dependencies
*** Fetching specta
*** Checking out specta at "v1.0.0"
*** xcodebuild output can be found in /var/folders/fv/z_s5t3cn095c3ff9m1vj6dt83942tn/T/carthage-xcodebuild.qKnQrR.log
*** Building scheme "Specta" in Specta.xcworkspace
*** Building scheme "Specta-iOS" in Specta.xcworkspace
A shell task failed with exit code 70:
xcodebuild: error: Failed to build workspace Specta with scheme Specta-iOS.
Reason: The run destination iPad 2 is not valid for Running the scheme 'Specta-iOS'.
```
Carthage aside, you can see that the underlying issue is actually in …
> Set Specta-iOS deployment target to 7.0

- README.md
I had these linking errors when I was trying to use Specta in my project. I've found the fix for the same issue here: http://support.getsocialize.com/socialize/topics/undefined_symbols_linker_error_when_upgrading_to_2_8_9#reply_13205010
> README: add a manual setup step to fix ___llvm_gcov_writeout linking errors

- Specta/Specta/XCTest+Private.h
- Specta/SpectaTests/TestHelper.h
- Specta/SpectaTests/TestHelper.m
PR for Issue #164 
Since the `XCTestObservationCenter` class is now public, when building for the new SDKs, only specific private method is exposed as a category. 
Tested Specta with `rake test` with both 10.10 and 10.11 SDKs and as cocoa pod with iOS 8 and 9 SDKs.
> XCTestObservationCenter private methods support for new SDK

- Specta/Specta/SPTExampleGroup.h
Retaining the parent and root strongly seems to result in a retain cycle for every example group
> Make root and parent weak

- Specta.podspec
This ensures Specta won't appear as available on watchOS.
> [Podspec] Specify platforms explicitly

- Specta.podspec
In Xcode 7, the `FRAMEWORK_SEARCH_PATHS` added by the Specta podspec cause build warnings. After experimenting removal of the values it adds to the generated xcconfig file, my targets build and tests run without warnings. I don't believe the pod requires any of these paths added by the podspec.
> remove framework_search_paths from podspec

- Specta/Specta/SPTSpec.m
Fixed https://github.com/facebook/xctool/issues/572.
Tested on https://github.com/arcam/CocoaUPnP/tree/xcode7.
> Make Specta compatible with xctool and Xcode 7.

- Specta/Specta.xcodeproj/project.pbxproj
- Specta/Specta/XCTest+Private.h
- Upgrades min version to iOS8 in framework (not supported before)
- Removes XCTestObservation protocol for iOS9+
> Xcode 7 + Carthage + Dynamic Modules

- Rakefile
I do not fully understand what happens here:
The behavior of executing test suites seems to have changed in Xcode 7. If not explicitly setting the build sdk to `iphonesimulator`, Xcode 7 will try to code sign the unit test bundle and the included frameworks even when running on a Simulator, whereas previous versions of xcode did not. 
Adding the `-sdk` flag to the xcodebuild call and telling it to use the iphonesimulator sdk fixes the current CI failures.
> Resolve CI issues in Xcode 7

- Specta.podspec
Fixes #178 for CocoaPods users.
> Disable bitcode for Specta when installed through Cocoapods

- Rakefile
- Specta/Specta.xcodeproj/project.pbxproj
This patchset addresses #167
Removes the flags to generate coverage files and instrument program flow
from the Xcode project and adds it only to the rake scripts
> Disables test coverage file in xcode proj

- Rakefile
In this [commit]( https://github.com/specta/specta/commit/806c901dddc84130b60fe825afb2a4cbdb9ae012)  I added support for specifying the code signing identity to support users who receive:
```
iPhone Developer: ambiguous (matches "iPhone Developer: XXX" and "iPhone Developer: YYY")
```
in the iOS code signing step.
With more experience under my belt, I think it is no longer necessary to use `SPT_CODE_SIGNING_IDENTITY` environment variable - the script should respond to `CODE_SIGN_IDENTITY` as `xcodebuild` does.
`SPT_CODE_SIGNING_IDENTITY` has been retained for backward compatibility.
> `rake` responds to CODE_SIGN_IDENTITY

- Specta/Specta/SPTSpec.m
Tiny typo, was fixing my own references, noticed this in the Pod.
> Typo: occured -> occurred

- CHANGELOG.md
- Specta/Specta/XCTestCase+Specta.m
Steps to reproduce:
1. Create new project
2. Add Specta
3. Write a standard `XCTestCase` with an `XCTestExpectation`, set a reasonable timeout and make sure it does not get fulfilled
4. 💥 Deadlock happens. Tests will never complete.
Please find a bug reproduced in this example project:
https://github.com/MatejBalantic/Specta-Deadlock
Just run the unit tests.
In this PR we make sure that Specta swizzling/dispatching only happens for subclasses of `SPTSpec`. 
I've run the tests in XCode 8 using the changes from this PR https://github.com/specta/specta/pull/213  and they pass. I am unable to write a test for this, as writing the test would mean I need to fail a test first. I was able to prove the change helps though.
If anyone has idea about how to add a test that expects and expectation to …
> Don’t dequeue failures on another thread for non Specta tests

- Specta/Specta/SpectaDSL.m
Dictionaries objects aren't release properly, when the test ends. This behavior causes problems when working with OpenGL based project.
> SpectaDSL: dictionary objects' life time bug fix.

- Specta/Specta/SpectaDSL.h
- Specta/Specta/SpectaTypes.h
- Specta/Specta/SpectaUtility.h
Specta currently doesn't compile with Xcode9, fixing functions to declare void fixes this.
> Make declarative with void to allow compilation with Xcode9

- Specta/Specta/SPTExampleGroup.m
- Specta/Specta/SpectaDSL.m
- Specta/Specta/XCTestCase+Specta.m
Fixes the Xcode 9 warning `This block declaration is not a prototype.`. See [this SO post](https://stackoverflow.com/questions/44473146/this-function-declaration-is-not-a-prototype-warning-in-xcode-9).
> Fix Xcode 9 warning about block declaration prototype
